### ISSUE TITLE
Feature: jekyll-archives replacement

### ISSUE THREAD

**Issue by mnot** [sorbits/glim#5]
Having archives is pretty much a requirement for blogs, but as a generator, it isn't compatible.

Any chance of a drop-in replacement?

**Comment by sorbits** [comment]
Glim can list all your categories, tags, or posts for a given category or tag, out of the box.

See [categories / tags](https://macromates.com/glim/collections#categories--tags) under collections.

You can see the archives for my [SIGPIPE blog here](https://sigpipe.macromates.com/archives/) or the [categories for the TextMate blog here](https://macromates.com/blog/categories/).

So I don’t think Glim needs a plug-in like `jekyll-archives`.
